export const dataStrong = {
  normal: ["figth"],
  figth: ["flying", "psychic", "fairy"],
  flying: ["rock", "electric", "ice"],
  poison: ["ground", "psychic"],
  ground: ["water", "grass", "ice"],
  rock: ["figth", "ground", "steel", "water", "grass"],
  bug: ["flying", "rock", "fire"],
  ghost: ["ghost", "dark"],
  stell: ["figth", "ground", "fire"],
  fire: ["ground", "rock", "water"],
  water: ["grass", "electric"],
  grass: ["flying", "poison", "bug", "fire", "ice"],
  electric: ["ground"],
  psychic: ["bug", "ghost", "dark"],
  ice: ["figth", "rock", "stell", "fire"],
  dragon: ["ice", "dragon", "fairy"],
  dark: ["figth", "bug", "fairy"],
  fairy: ["poison", "stell"],
};

export const dataWeak = {
  normal: ["rock", "ghost", "steel"],
  figth: ["flying", "poison", "bug", "ghost", "psychic", "fairy"],
  flying: ["rock", "steel", "electric"],
  poison: ["poison", "ground", "rock", "ghost", "steel"],
  ground: ["flying", "bug", "grass"],
  rock: ["figth", "ground", "steel"],
  bug: ["figth", "poison", "ghost", "steel", "fire", "fairy"],
  ghost: ["normal", "dark"],
  stell: ["steel", "fire", "water", "electric"],
  fire: ["rock", "fire", "water", "dragon"],
  water: ["water", "grass", "dragon"],
  grass: ["flying", "poison", "bug", "steel", "fire", "grass", "dragon"],
  electric: ["ground", "grass", "electric", "dragon"],
  psychic: ["steel", "psychic", "dark"],
  ice: ["steel", "fire", "water", "ice"],
  dragon: ["steel", "fairy"],
  dark: ["figth", "dark", "fairy"],
  fairy: ["poison", "stell", "fire"],
};
